### ISSUE TITLE
design pages and popups

### ISSUE THREAD

**Issue by PSmigielski** [PSmigielski/pizzeria#17]
- [x] user actions menu (logout, settings etc.)
- [x] pizza creator
- [x] half pizza order
- [x] verify user popup
- [x] cart
- [x] loading screen 
- admin panel
  -  page for managing products
      - [x] add
      - [x] delete
      - [x] edit
  - page for managing categories
    - [x] add
    - [x] delete
    - [x] edit
  - page for managing discounts
    - [x] add
    - [x] delete
  - page for managing images
      - [x] add
      - [x] delete
  - page for managing user roles
    - [x] edit role for given user
  - page for managing toppings for pizzas
    - [x] add
    - [x] delete
    - [x] edit
- [x] 404 page
- [x] order summary
- [x] order form 
- user panel
  - [x] show user data
  - [x] edit user data
  - [x] remove account
  - [x] show finished transactions and its details

**Comment by jakubwelninski** [comment]
A lot of work m8!
